### ISSUE TITLE
Live demo link doesn't work

### ISSUE THREAD

**Issue by divyagnan** [cbartram/nanoleaf-layout#26]
The live demo link https://cbartram.github.io/nanoleaf-layout/ seems to just link to the readme. The `.travis.yml` suggests that the demo app from the demo folder is being deployed so maybe the link should point to that instead?

**Comment by cbartram** [comment]
Your right I'm gonna take a look and see if I can fix it up!

**Comment by cbartram** [comment]
This has been resolved the new link is updated in the README!
